apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .ProjectName }}-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .ProjectName }}
  template:
    metadata:
      labels:
        app: {{ .ProjectName }}
    spec:
      containers:
        - name: {{.ProjectName}}
          image: {{.ProjectName}}:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8090
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .ProjectName }}-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .ProjectName }}
  ports:
    - port: 8080
      targetPort: 8090