- name: Simple Module Project
  reference: https://go.dev/ref/mod
  url: https://github.com/denizgursoy/go-touch-projects/raw/main/package/empty.tar.gz
  language: go
  questions:
    - direction: Do you want Dockerfile?
      canSkip: true
      choices:
        - choice: Yes
          dependencies:
            - github.com/labstack/echo/v4
            - github.com/gorilla/mux
            - github.com/gin-gonic/gin
          files:
            - url: https://raw.githubusercontent.com/denizgursoy/go-touch-projects/main/Dockerfile
              pathFromRoot: Dockerfile
          values:
            isDocker: true
    - direction: Do you want Kubernetes Deployment files?
      canSkip: true
      choices:
        - choice: Yes
          files:
            - url: https://raw.githubusercontent.com/denizgursoy/go-touch-projects/main/k8s-deployment.yaml
              pathFromRoot: app-deployment.yaml
          values:
            isKubernetes: true
    - direction: Do you want Makefile?
      canSkip: true
      choices:
        - choice: Yes
          files:
            - url: https://raw.githubusercontent.com/denizgursoy/go-touch-projects/main/Makefile
              pathFromRoot: Makefile
- name: Standard Project Layout
  reference: https://github.com/golang-standards/project-layout
  url: https://github.com/denizgursoy/go-touch-projects/raw/main/package/standard.tar.gz
  language: go
  questions:
    - direction: Do you want Dockerfile?
      canSkip: true
      choices:
        - choice: Yes
          files:
            - url: https://raw.githubusercontent.com/denizgursoy/go-touch-projects/main/DefaultDockerfile
              pathFromRoot: /build/package/Dockerfile
          values:
            isDocker: true
    - direction: Do you want Kubernetes Deployment files?
      canSkip: true
      choices:
        - choice: Yes
          files:
            - url: https://raw.githubusercontent.com/denizgursoy/go-touch-projects/main/k8s-deployment.yaml
              pathFromRoot: /deployments/app-deployment.yaml
          values:
            isKubernetes: true
    - direction: Do you want Makefile?
      canSkip: true
      choices:
        - choice: Yes
          files:
            - url: https://raw.githubusercontent.com/denizgursoy/go-touch-projects/main/DefaultMakefile
              pathFromRoot: Makefile